# To run this file, RUN:
# docker compose up -d 

version: "3.8"
services:
  farawayfarmer:
    restart: unless-stopped
    build:
      context: ./psd2
      dockerfile: dockerfile
    image: farawayfarmer
    environment:
      - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "80:8000"
    depends_on:
      - db
      - nearbyfarmer

  nearbyfarmer:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: dockerfile
    image: nearbyfarmer
    environment:
      - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}

  db-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080