# Generated by Django 5.0.2 on 2024-03-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyfarmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
