# Generated by Django 5.0.2 on 2024-03-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyfarmer', '0002_alter_plant_options_alter_sensordata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plant',
            table='plant',
        ),
        migrations.AlterModelTable(
            name='sensordata',
            table='sensordata',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
