# Generated by Django 4.2.11 on 2024-03-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_watered", models.DateField()),
                ("water_level", models.IntegerField()),
                ("floor_level", models.IntegerField()),
            ],
        ),
    ]
