# Generated by Django 5.0.2 on 2024-03-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farawayfarmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plant',
            table='plant',
        ),
        migrations.AlterModelTable(
            name='sensordata',
            table='sensordata',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
