FROM python:3.11-slim
ADD . .
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  
RUN pip install -r requirements.txt  
EXPOSE 8000  
RUN python manage.py makemigrations
CMD python manage.py runserver 0.0.0.0:8000